/**
 * Hai sidebar thay vì một.
 *
 * Giáo trình .NET chiếm 277/421 file docs. Gộp chung một sidebar thì người
 * đang học phải cuộn qua bảy mảng không liên quan (LeetCode, AWS, hệ điều
 * hành...) mới tới phần mình cần, còn người tra cứu thì ngược lại.
 *
 * `tutorialSidebar` liệt kê tường minh từng thư mục chứ không autogenerate cả
 * `.`: thêm một mảng docs mới phải là quyết định có ý thức, không tự lọt vào.
 *
 * Cố ý GIỮ tên `tutorialSidebar` cho nhánh tra cứu: khoảng 37 khoá dịch trong
 * i18n có dạng `sidebar.tutorialSidebar.category.*`, đổi tên là chúng thành
 * khoá chết và bản tiếng Anh mất nhãn danh mục mà build vẫn xanh.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  dotnetSidebar: [
    { type: 'autogenerated', dirName: '09-dotnet-backend-zero-to-senior' },
  ],

  tutorialSidebar: [
    'index',
    { type: 'autogenerated', dirName: '01-operating-system' },
    { type: 'autogenerated', dirName: '02-web-security' },
    { type: 'autogenerated', dirName: '04-leetcode' },
    { type: 'autogenerated', dirName: '05-k6' },
    { type: 'autogenerated', dirName: '06-database' },
    { type: 'autogenerated', dirName: '07-aws-cloud-practitioner-essentials' },
    { type: 'autogenerated', dirName: '08-agent-skills' },
    'seo-geo-guide',
  ],
};

module.exports = sidebars;
