/**
 * Ba sidebar thay vì một.
 *
 * Giáo trình .NET chiếm 277/421 file docs. Gộp chung một sidebar thì người
 * đang học phải cuộn qua bảy mảng không liên quan (LeetCode, AWS, hệ điều
 * hành...) mới tới phần mình cần, còn người tra cứu thì ngược lại.
 *
 * Cố ý GIỮ tên `tutorialSidebar` cho nhánh tra cứu: khoảng 37 khoá dịch trong
 * i18n có dạng `sidebar.tutorialSidebar.category.*`, đổi tên là chúng thành
 * khoá chết và bản tiếng Anh mất nhãn danh mục mà build vẫn xanh.
 */

// @ts-check

/**
 * Bọc một thư mục docs thành category, lấy nhãn và link từ chính `_category_.json`.
 *
 * BẮT BUỘC phải bọc. Khi `autogenerated` lấy một thư mục con LÀM GỐC, Docusaurus
 * sinh ra nội dung bên trong chứ không tạo category cho chính thư mục đó — nên
 * `_category_.json` bị bỏ qua và trang `generated-index` của nó biến mất. Cả 8
 * thư mục docs đều khai `link.slug`, nên thiếu lớp bọc này là mất 8 route, kéo
 * theo mọi liên kết trỏ tới chúng hỏng và build đỏ.
 *
 * Đọc lại từ file thay vì chép tay để metadata không trôi khỏi nhau.
 */
function fromDir(dirName) {
    const meta = require(`./docs/${dirName}/_category_.json`);
    /** @type {any} */
    const category = {
        type: 'category',
        label: meta.label,
        items: [{ type: 'autogenerated', dirName }],
    };
    if (meta.link) category.link = meta.link;
    if (typeof meta.collapsed === 'boolean') category.collapsed = meta.collapsed;
    return category;
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    dotnetSidebar: [fromDir('09-dotnet-backend-zero-to-senior')],

    // Khoá SQL 30 ngày tách riêng, cùng lý do với khoá .NET: người đang học
    // theo ngày không nên phải cuộn qua LeetCode và WebGoat mới tới bài kế.
    //
    // Bọc cả `06-database` chứ không trỏ thẳng vào `learn-sql-in-30-days`, vì
    // hai lẽ:
    //
    // 1. `06-database` có `link.slug` riêng (/database). Trỏ thẳng vào thư mục
    //    con thì `_category_.json` ngoài bị bỏ qua và route đó biến mất.
    //
    // 2. Không thể để `06-database` nằm ở cả đây lẫn tutorialSidebar. Docusaurus
    //    KHÔNG báo lỗi khi một doc thuộc hai sidebar — sidebars/utils.js dựng
    //    map docId -> sidebarName bằng Object.fromEntries, nên bản sau lặng lẽ
    //    đè bản trước. Người đọc sẽ bị nhảy sang sidebar kia giữa chừng mà build
    //    vẫn xanh.
    //
    // Tài liệu database không thuộc khoá học, khi có, cứ thêm thẳng vào
    // `docs/06-database/` — chúng sẽ hiện trong menu này, cạnh khoá học. Lúc đó
    // cân nhắc đổi nhãn navbar từ "Khoá SQL" sang "Database" cho đúng phạm vi.
    //
    // Không chuyển khoá sang thư mục gốc riêng: 32 bài đều dùng `slug` TƯƠNG
    // ĐỐI, nên URL phụ thuộc đường dẫn thư mục. Đổi chỗ là đổi cả 32 URL đã
    // được Google lập chỉ mục.
    sqlSidebar: [fromDir('06-database')],

    // Liệt kê tường minh chứ không autogenerate cả `.`: thêm một mảng docs mới
    // phải là quyết định có ý thức, không tự lọt vào.
    tutorialSidebar: [
        'index',
        fromDir('01-operating-system'),
        fromDir('02-web-security'),
        fromDir('04-leetcode'),
        fromDir('05-k6'),
        fromDir('07-aws-cloud-practitioner-essentials'),
        fromDir('08-agent-skills'),
        'seo-geo-guide',
    ],
};

module.exports = sidebars;
