/**
 * Hai sidebar thay vì một.
 *
 * Giáo trình .NET chiếm 277/421 file docs. Gộp chung một sidebar thì người
 * đang học phải cuộn qua bảy mảng không liên quan (LeetCode, AWS, hệ điều
 * hành...) mới tới phần mình cần, còn người tra cứu thì ngược lại.
 *
 * Cố ý GIỮ tên `tutorialSidebar` cho nhánh tra cứu: khoảng 37 khoá dịch trong
 * i18n có dạng `sidebar.tutorialSidebar.category.*`, đổi tên là chúng thành
 * khoá chết và bản tiếng Anh mất nhãn danh mục mà build vẫn xanh.
 */

// @ts-check

/**
 * Bọc một thư mục docs thành category, lấy nhãn và link từ chính `_category_.json`.
 *
 * BẮT BUỘC phải bọc. Khi `autogenerated` lấy một thư mục con LÀM GỐC, Docusaurus
 * sinh ra nội dung bên trong chứ không tạo category cho chính thư mục đó — nên
 * `_category_.json` bị bỏ qua và trang `generated-index` của nó biến mất. Cả 8
 * thư mục docs đều khai `link.slug`, nên thiếu lớp bọc này là mất 8 route, kéo
 * theo mọi liên kết trỏ tới chúng hỏng và build đỏ.
 *
 * Đọc lại từ file thay vì chép tay để metadata không trôi khỏi nhau.
 */
function fromDir(dirName) {
    const meta = require(`./docs/${dirName}/_category_.json`);
    /** @type {any} */
    const category = {
        type: 'category',
        label: meta.label,
        items: [{ type: 'autogenerated', dirName }],
    };
    if (meta.link) category.link = meta.link;
    if (typeof meta.collapsed === 'boolean') category.collapsed = meta.collapsed;
    return category;
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    dotnetSidebar: [fromDir('09-dotnet-backend-zero-to-senior')],

    // Liệt kê tường minh chứ không autogenerate cả `.`: thêm một mảng docs mới
    // phải là quyết định có ý thức, không tự lọt vào.
    tutorialSidebar: [
        'index',
        fromDir('01-operating-system'),
        fromDir('02-web-security'),
        fromDir('04-leetcode'),
        fromDir('05-k6'),
        fromDir('06-database'),
        fromDir('07-aws-cloud-practitioner-essentials'),
        fromDir('08-agent-skills'),
        'seo-geo-guide',
    ],
};

module.exports = sidebars;
